server:
  port: 8020
spring:
  application:
    name: eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dingzeliang/springCloudDemo.git
          username: flightbefore@sina.com
          password: DZLbz13095917047